### ISSUE TITLE
CloudFormation stack to deploy lambda functions, S3 bucket, and Notebook instance with appropriate IAM roles is not accessible. 

### ISSUE THREAD

**Issue by bharathshivashankar** [aws-samples/annotate-medical-images-in-dicom-server-and-build-ml-models-on-amazon-sagemaker#2]
link: S3 URL: https://orthanc-on-aws.s3.amazonaws.com/sagemaker_resources.yaml

error: S3 error: Access Denied For more information check http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html

**Comment by vinodkmrr** [comment]
Hi ,

I am also getting the same error as mentioned above : "S3 error: Access denied " when accessing the S3 URL link https://orthanc-on-aws.s3.amazonaws.com/sagemaker_resources.yaml . Please help us on this

**Comment by MasazI** [comment]
Hi,
You can use a file below in this repo instead of link you mentioned.
sagemaker-groundtruth/sagemaker_resources.yaml

**Comment by flamingofugang** [comment]
Yes, the same file is in this repo. And that download link should work now. Sorry for the issue.
